name: Build and upload release to PyPI

on:
  release:
    types:
      - published
  # delete after testing
  pull_request:
    branches: [master]

jobs:
  oorb_data:
    uses: ./.github/workflows/oorb_data.yml

  wheels:
    name: Build ${{ matrix.pyversion }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-latest]
        pyversion: ["3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: oorb/

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Restore cached ephemeris data
        uses: actions/cache/restore@v4
        with:
          key: oorb_data
          path: /tmp/cache/oorb_data
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Set environment
        run: |
          echo "OORB_DATA=/tmp/cache/oorb_data" >> "$GITHUB_ENV"
          echo "MACOSX_DEPLOYMENT_TARGET=15.0" >> "$GITHUB_ENV"

      - name: Build wheels
        run: |
          ls
          cd oorb
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.pyversion }}
          path: dist/*.whl

      - name: Install pyoorb from wheel
        # First, install with --no-index to make sure we don't hit up PyPI and
        # only use the local wheel. Use --no-deps, because we don't have a local
        # copy of any dependencies. Once we are sure the local wheel works,
        # install dependencies by repeating the command, but this time allowing
        # the index and deps.
        run: |
          pip install --no-index --no-deps --find-links dist/ pyoorb
          pip install --find-links dist/ pyoorb

      - name: Execute tests
        run: |
          python -c "import pyoorb; print('Import pyoorb success.')"
          python oorb/python/test.py

  # build_sdist:
  #   # Make a plain source distribution with nothing precompiled.
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Build SDist
  #       run: pipx run build --sdist
  # - name: Get wheels
  #   uses: actions/download-artifact@v5
  #   with:
  #     name: wheels-${{ matrix.os }}-${{ matrix.pyversion }}
  #     path: dist/*.whl
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: sdist
  #         path: dist/*.tar.gz

  # upload_all:
  #   name: Upload release to PyPI
  #   needs:
  #     - build_sdist
  #     - test_wheels
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/legacy/

  #   if: github.event_name == 'release' && github.event.action == 'published'

  #   permissions:
  #     id-token: write

  #   steps:
  #     - uses: actions/download-artifact@v5
  #       with:
  #         merge-multiple: true
  #         pattern: wheels-*
  #         path: ./sdist/

  #     - uses: actions/download-artifact@v5
  #       with:
  #         name: sdist
  #         path: ./sdist/

  #     - uses: pypa/gh-action-pypi-publish@release/v1
