name: Build and upload release to PyPI

on:
  release:
    types:
      - published

jobs:
  wheels:
    name: Build ${{ matrix.pyversion }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        pyversion: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu
            architecture: x86_64
          - os: ubuntu
            architecture: aarch64
          - os: macos
            architecture: x86_64
          - os: macos
            architecture: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
        if: runner.os == 'Linux' && matrix.architecture == 'aarch64'
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: $${{ matrix.pyversion }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_BUILD: "${{ matrix.pyversion }}*"
          CIBW_ARCHS: "${{ matrix.architecture }}"
        with:
          output-dir: wheelhouse
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.architecture }}
          path: wheelhouse/*.whl

  build_ephem:
    name: Build ephemeris data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install gfortran liblapack-dev meson ninja-build
      - name: Compile oorb
        run: |
          ./configure gfortran opt
          make -j2
      - name: Build ephemerides
        run: |
          cd data/JPL_ephemeris
          make -j2
          make test
      - name: Supply data to later tests
        uses: actions/upload-artifact@v4
        with:
          name: oorb_data
          path: |
            ./data
            !./data/JPL_ephemeris

  # test all os, architecture, python combinations, the steps branch depending
  # on if the architecture is (linux/)aarch64 or not
  test_wheels:
    name: Test ${{ matrix.pyversion }}/${{ matrix.os }}
    needs: [wheels, build_ephem]
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        pyversion: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu
            architecture: x86_64
          - os: ubuntu
            architecture: aarch64
          - os: macos
            architecture: x86_64
          - os: macos
            architecture: arm64
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: $${{ matrix.pyversion }}
      - name: Checkout oorb for python/test.py
        uses: actions/checkout@v6
        with:
          path: ./_oorb
      - name: Get wheels
        uses: actions/download-artifact@v5
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.architecture }}
          path: /tmp/artifacts/wheels
      - name: Get oorb data
        uses: actions/download-artifact@v5
        with:
          name: oorb_data
          path: /tmp/artifacts/oorb_data
      - name: Setup QEMU
        if: matrix.architecture == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Run tests in container
        if: matrix.architecture == 'aarch64'
        # Runs in emulation, so this can be very slow!
        run: |
          export DOCKER_IMAGE="arm64v8/python:${{ matrix.pyversion }}"
          docker pull --platform linux/arm64 $DOCKER_IMAGE
          docker run \
            --platform linux/arm64 \
            --volume /tmp/artifacts:/tmp/artifacts \
            --volume $PWD/_oorb:/tmp/oorb_latest \
            --env OORB_DATA=/tmp/artifacts/oorb_data \
            $DOCKER_IMAGE \
            /bin/bash -c "
            pip install --no-index --no-deps --find-links /tmp/artifacts/wheels pyoorb && \
            pip install --find-links /tmp/artifacts/wheels pyoorb && \
            python /tmp/oorb_latest/python/test.py"
      - name: Install pyoorb from wheel
        if: ${{ matrix.architecture != 'aarch64' }}
        run: |
          # First, install with --no-index to make sure we don't hit up PyPI and only
          # use the local wheel. Use --no-deps, because we don't have a local copy of
          # any dependencies.
          pip install --no-index --no-deps --find-links /tmp/artifacts/wheels pyoorb
          # Now that we are sure the local wheel works, install dependencies by repeating
          # the command, but this time allowing the index and deps.
          pip install --find-links /tmp/artifacts/wheels pyoorb
      - name: Try importing pyoorb
        if: ${{ matrix.architecture != 'aarch64' }}
        run: |
          export OORB_DATA=/tmp/artifacts/oorb_data
          python -c "import pyoorb; print('success.')"
      - name: Execute tests
        if: ${{ matrix.architecture != 'aarch64' }}
        run: |
          export OORB_DATA=/tmp/artifacts/oorb_data
          python ./_oorb/python/test.py

  build_sdist:
    # Make a plain source distribution with nothing precompiled.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload_all:
    name: Upload release to PyPI
    needs:
      - build_sdist
      - test_wheels
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/legacy/
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true
          pattern: wheels-*
          path: ./sdist/
      - uses: actions/download-artifact@v5
        with:
          name: sdist
          path: ./sdist/
      - uses: pypa/gh-action-pypi-publish@release/v1
